CREATE ROLE clane WITH
	LOGIN
	SUPERUSER
	CREATEDB
	CREATEROLE
	INHERIT
	NOREPLICATION
	CONNECTION LIMIT -1
	PASSWORD 'clane';

CREATE DATABASE clanedb
    WITH
    OWNER = clane
    ENCODING = 'UTF8'
    CONNECTION LIMIT = -1;
